// src/app/features/schedule/components/schedule.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-schedule',
  template: `
    <div class="space-y-8">
      <app-page-header 
        title="Horaires" 
        subtitle="Les horaires d'ouverture et périodes de fermeture de la MAM"
      />
      <app-page-content>
        <div class="space-y-4">
          <p class="text-lg text-gray-600">
            La MAM est ouverte du lundi au vendredi de 6h30 à 18h30 et fermée 8 semaines dans l'année.
          </p>
          <p class="text-lg text-gray-600 italic">
            Les horaires ne sont pas fixes.
          </p>
        </div>
      </app-page-content>
    </div>
  `
})
export class ScheduleComponent { }

// src/pages/schedule/index.jsx
import React from 'react';
import PageHeader from '@/components/PageHeader';
import PageContent from '@/components/PageContent';
import { Schedule } from './components/schedule';

export function SchedulePage() {
  return (
    <div className="space-y-8">
      <PageHeader 
        title="Horaires" 
        subtitle="Les horaires d'ouverture et périodes de fermeture de la MAM"
      />
      <PageContent>
        <Schedule />
      </PageContent>
    </div>
  );
}
