// src/app/shared/components/button/button.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-button',
  standalone: true,
  imports: [CommonModule],
  template: `
    <button
      [type]="type"
      [disabled]="disabled"
      class="inline-flex items-center justify-center rounded-md px-4 py-2 text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 disabled:opacity-50"
      [ngClass]="{
        'bg-primary-600 text-white hover:bg-primary-700': variant === 'primary',
        'bg-white text-primary-600 border border-primary-200 hover:border-primary-400': variant === 'secondary'
      }"
    >
      <ng-content></ng-content>
    </button>
  `
})
export class ButtonComponent {
  @Input() type: 'button' | 'submit' = 'button';
  @Input() variant: 'primary' | 'secondary' = 'primary';
  @Input() disabled = false;
}

// src/components/ui/Button.jsx
import React from 'react';

export default function Button({ children, variant = 'primary', ...props }) {
  const variants = {
    primary: 'bg-green-600 text-white hover:bg-green-700',
    secondary: 'bg-white text-green-600 border border-green-200 hover:border-green-400'
  };

  return (
    <button
      className={`px-6 py-3 font-semibold rounded-lg shadow-md 
        focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2
        transition-all ${variants[variant]}`}
      {...props}
    >
      {children}
    </button>
  );
}
